name: 'Setup Reconocimiento Tool Action'
description: 'Sets up a testing recognition tool (Monkey or Ripper) in a target repository'

inputs:
  tool:
    description: 'Recognition tool to setup (monkey or ripper)'
    required: true
    type: choice
    options:
      - monkey
      - ripper
  repository:
    description: 'Target repository to update'
    required: true
  token:
    description: 'GitHub token with repository access'
    required: true
    default: ${{ github.token }}

permissions:
  contents: write
  packages: read

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "lts/iron"

    - name: Checkout Target Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        path: target-repo

    - name: Checkout Tool Repo
      uses: actions/checkout@v4
      with:
        repository: Uniandes-MISW4103/proyecto-${{ inputs.tool }}-base
        path: tool-repo

    - name: Copy Base Contents
      shell: bash
      run: |
        echo "Copying files from ${{ inputs.tool }}-repo to target-repo"
        rsync -a --exclude='.git' --exclude='package-lock.json' tool-repo/ target-repo/reconocimiento/misw-4103-${{ inputs.tool }}/
        echo "Files copied successfully"

    - name: Set Framework Scripts
      shell: bash
      run: |
        echo "Setting up framework scripts for ${{ inputs.tool }} to main package.json"
        cd target-repo
        if [ "${{ inputs.tool }}" = "monkey" ]; then
          npm pkg set scripts.monkey:test="npm run test -w misw-4103-monkey"
          npm pkg set scripts.monkey:ui="npm run test:ui -w misw-4103-monkey"
        else
          npm pkg set scripts.ripper:prepare="npm run prepare -w misw-4103-ripper"
          npm pkg set scripts.ripper:test="npm run test -w misw-4103-ripper"
          npm pkg set scripts.ripper:ui="npm run test:ui -w misw-4103-ripper"
        fi

    - name: Commit Changes to Target
      shell: bash
      run: |
        cd target-repo
        git config user.name "Equipo Docente MISW4103"
        git config user.email "equipo-docente-misw4103@uniandes.edu.co"
        git add .
        git commit -m "chore: initial setup for ${{ inputs.tool }}"
        git push origin HEAD